default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  reconnect: true
  pool: 5

development:
  <<: *default
  username: codebase
  password: password
  host: postgres
  database: rails_development

test:
  <<: *default
  username: codebase
  password: password
  host: postgres
  database: application_test

production:
  <<: *default
  username: codebase
  url: <%= ENV['DATABASE_URL'] %>
